version: '3'

services:

  zalenium:
    image: elgalu/selenium
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /d/Users/mithun/temp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --videoRecordingEnabled true
            --startTunnel true
    environment:
        HUB_HOST: 192.168.10.37
        HUB_PORT_4444_TCP_ADDR: hub
        HUB_PORT_4444_TCP_PORT: 4444