# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome4:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb

    environment:

      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "100:5900"
      
  chrome5:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb

    environment:

      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "101:5900"
      
   chrome6:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb

    environment:

      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "102:5900"

