version: "3"

services:

  hub:
    image: selenium/hub
    container_name: selenium-hub
    environment:
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 30000
      GRID_BROWSER_TIMEOUT: 30000
      GRID_TIMEOUT: 30000

  node1:
    image: selenium/node-chrome-debug
    container_name: web-automation_chrome
    depends_on:
      - hub

    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 5
      platform: ANY

    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "32770:5900"
    links:
      - hub

  node2:
    image: selenium/node-chrome-debug
    container_name: web-automation_chrome1
    depends_on:
      - hub

    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 5
      platform: ANY

    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "32771:5900"
    links:
      - hub

  node3:
    image: selenium/node-chrome-debug
    container_name: web-automation_chrome2
    depends_on:
      - hub

    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 5
      platform: ANY


    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "32772:5900"
    links:
      - hub
